### ISSUE TITLE
Support of the german language

### ISSUE THREAD

**Issue by MaxBenChrist** [pires/android-obd-reader#105]
Hello,

first let me say: Great project! I already had a lot of fun working with the app.

I am planning to implement some features that I need. I do not have much experience with android development but I am eager to learn. I will open several issues to divide my features semantically. You have to decide if they are of interest for you as well. 

I am looking forward to work with you. :)

The first issue is to implement a full support of the german language.

Greetings 

Max

**Comment by pires** [comment]
Hi @MaxBenChrist! Thanks for contributing back. I am open to review your PRs and so far your issues are on pair with my personal guidelines.
