### ISSUE TITLE
Batch wise upload of the trip data when the device is connected to WIFI.

### ISSUE THREAD

**Issue by MaxBenChrist** [pires/android-obd-reader#106]
To save data in a mobile data plan, the trips should only uploaded when the device is connected to a WIFI. This should work even when the application is not used.

I would use an AlarmManager to launch the service periodically and then check for wifi connection.

**Comment by pires** [comment]
People should be able to set whether they want to upload `on WiFi connection only` or not.

**Comment by Pho3niX90** [comment]
Has anyone started on this? This should be relatively easy to do.

**Comment by MaxBenChrist** [comment]
yes, i already implemented it.

**Comment by pires** [comment]
Awesome @MaxBenChrist! Bring it on :)
