### ISSUE TITLE
Test obd-java-api 1.0-RC2

### ISSUE THREAD

**Issue by pires** [pires/android-obd-reader#108]
@nomwerp @amouly care to help? PR submitted.

**Comment by nomwerp** [comment]
builds and runs but getting  "7F 01 12" as response from several commands which i guess is the new UnsupportedCommandException?

**Comment by nomwerp** [comment]
we should also add the new commands to https://github.com/pires/android-obd-reader/blob/master/src/main/java/com/github/pires/obd/reader/config/ObdConfig.java so that they become available

**Comment by nomwerp** [comment]
to answer my own question:

> getting "7F 01 12" as response from several commands which i guess is the new  UnsupportedCommandException?

yes it is , since it is now actually throwing an exception the raw response is shown. we should probably make it more pretty by replacing  "7F 01 12" with "NA" or "-"  or something like that (and possibly maybe disabling unsupported command for remaining of the live data collection cycle?)

**Comment by pires** [comment]
@nomwerp want to take care of that? Would be happy to merge. I'm traveling for a couple weeks and my availability for this is close to none.

**Comment by nomwerp** [comment]
yes will have a look , in any case I'll merge the pull request and raise issue for adding new commands and prettifying unsupported command results

**Comment by pires** [comment]
Can you test RC3. Just released it but may take a while to sync to Maven Central.

**Comment by nomwerp** [comment]
commented on pires/obd-java-api#34

**Comment by pires** [comment]
Thank you. Will close this and wait for @anti43 feedback on #34.
