### ISSUE TITLE
show more friendly response for unsupported commands

### ISSUE THREAD

**Issue by nomwerp** [pires/android-obd-reader#112]
from  #108 : 

since move to obd-java-api 1.0-RC2 i'm getting "7F 01 12" as response from several commands which is due to the new UnsupportedCommandException  , since it is now actually throwing an exception the raw response is shown. we should make it more pretty by replacing "7F 01 12" with "NA" or "-" or something like that (and possibly maybe disabling unsupported command for remaining of the live data collection cycle?)

**Comment by nomwerp** [comment]
with obd-java-api 1.0-RC3 it now returns "7F0112" instead of "7F 01 12" ...

**Comment by pires** [comment]
Good point here. The buffer processing stuff on the API changed a bit and it's a bit confusing, so I'd say that for now we should change how this app handles strings. I'm sorry for breaking this, but I can't pay as much attention as I want for the next two weeks :(
