### ISSUE TITLE
VinObdCommand issue

### ISSUE THREAD

**Issue by Pho3niX90** [pires/android-obd-reader#119]
Hi.

I tried out the vin and seems that it returns a 70 digit number instead of a vin number. Ex "4902010000005749020242534548490203393230334902043043473949020539383331"

**Comment by nomwerp** [comment]
thangs for testing, i believe this had just been fixed in pires/obd-java-api#50

**Comment by Pho3niX90** [comment]
Awesome. I will test that and revert back

**Comment by Pho3niX90** [comment]
This is working like a charm now.

**Comment by pires** [comment]
I'll release `obd-java-api` RC5 later today and upgrade the dependency version here.

**Comment by Pho3niX90** [comment]
Could we please reopen this? I tried it on my 750 today and it couldn't properly pick up the vin, instead it returned "IWIBLI82I61I1".

**Comment by nomwerp** [comment]
is there a difference between the version you tested an RC5?

**Comment by pires** [comment]
See https://github.com/pires/obd-java-api/commit/d5474dce0556d3eca1707a5b41033edbc0600c94. That should be the properly formatted VIN.

**Comment by pires** [comment]
Calling @anti43 on this one.

**Comment by anti43** [comment]
@nomwerp yes with this fix it works properly for me. one way to screw it is if the obd device is sending headers, which you can turn off issuing a command AT H0 which is not yet implemented in RC5. Had this issue yesterday.

**Comment by Pho3niX90** [comment]
Yes I am using the correct version. This is working on the one car but not the other.

**Comment by anti43** [comment]
when you connect via obd terminal, what is the raw response?

2015-07-22 8:04 GMT+02:00 Pho3niX90 <notifications@github.com>:

**Comment by Pho3niX90** [comment]
I haven't tested. Which obd terminal do you suggest

**Comment by anti43** [comment]
obd terminal from play store

2015-07-22 8:32 GMT+02:00 Pho3niX90 <notifications@github.com>:

**Comment by Pho3niX90** [comment]
I added the headers command and that solved it. Thank you.

**Comment by Pho3niX90** [comment]
Receiving this on an M3 = 0140:4902015742531:574439323031302:50593335393632

**Comment by anti43** [comment]
see https://github.com/pires/obd-java-api/issues/54

**Comment by Pho3niX90** [comment]
Is there a possible solution to this? This -> 4902015742531:574439323031302:50593335393632
is the vin

**Comment by anti43** [comment]
yes there is a solution, see the referenced issue. the presented solution is not ideal as discussed, but if it works for you it might be ok

**Comment by Pho3niX90** [comment]
That solution just yields hex code returned

**Comment by anti43** [comment]
then go ahead and use it

```
 StringBuilder b = new StringBuilder();

 for (int i = 2; i < buffer.size(); i++) {
      b.append(new Character((char) buffer.get(i).intValue()).toString());
  }
            
 String vin = b.toString().replaceAll("[\u0000-\u001f]", "");
```

See a complete solution here (parses those ":" separated vins and teh other multiline one):

https://github.com/anti43/obd-java-api/blob/master/src/main/java/com/github/pires/obd/commands/control/VinObdCommand.java

**Comment by Pho3niX90** [comment]
I have implemented your solution, vin now comes back IIBSI92I0JI68

**Comment by Pho3niX90** [comment]
Please ignore the above. Just noticed this is on an E46 m3. I am testing the app on a fleet of BMWs

**Comment by anti43** [comment]
can you post the complete raw response

**Comment by Pho3niX90** [comment]
So it has creeped up again with another car. IWIBCI38I05I5

**Comment by pires** [comment]
Please, try the latest code. Closing this but will reopen if there's feedback about it not being fixed.
