### ISSUE TITLE
VinObdCommand get vin only once per session

### ISSUE THREAD

**Issue by Pho3niX90** [pires/android-obd-reader#123]
Since the vin will never change on a vehicle, I think a improvement will be to only get the vin once at the start of a logging session. If this is currently the case I apologize for creating this.

This will bring down the overhead on polling.

**Comment by nomwerp** [comment]
i think this applies in general , for example a unsupported command in unlikely to suddenly become supported. so maybe if a command return same value x number of times don't request it again in that session ?  but that might not be a good idea for all commands

**Comment by Pho3niX90** [comment]
Yes that would be the ideal solution. There is a class that checks the supported PIDs, when a session is started it would be good to run this first and store the PID's with the vin, so next time it knows what can be polled and what can't.

**Comment by nomwerp** [comment]
or maybe move both the preference dialogue, i.e. before (only show available) or after(check selected) selecting the commands.  and for vin, since we already have a setting for vin there we could add option to get it from the car.

**Comment by Pho3niX90** [comment]
I will try to add the feature, I am craving for faster data

**Comment by pires** [comment]
@Pho3niX90 you're rocking the place! Keep it up.
