### ISSUE TITLE
PHP Server version

### ISSUE THREAD

**Issue by Pho3niX90** [pires/android-obd-reader#124]
I have created a php version of the upload server. Not sure how I can contribute it to the project?

**Comment by nomwerp** [comment]
yep did the same thing ;) not sure where to put it either

**Comment by Pho3niX90** [comment]
Here you go. https://github.com/Pho3niX90/OBD2-SERVER

Its extremely simple, just add credentials and it will automatically create the database and add the new columns, if new readings gets added it will automatically create the new columns as well.

**Comment by pires** [comment]
@Pho3niX90 is that a _server_? Been a while since I coded PHP but I do not see any REST related code but rather a PHP script that one can run in his terminal.

**Comment by Pho3niX90** [comment]
@pires yes it is a server. That's the end url, have been running it. 

The brilliant part about it is that it automatically creates the tables and fields as required, so maintenance on it is null

**Comment by carpiko1010** [comment]
I am using this php code on my server, but there is no entries in the mysql table, the tables are created but no data is getting entered into it from the obd app.
