### ISSUE TITLE
Reformat code according to Android IDE defaults.

### ISSUE THREAD

**Issue by pires** [pires/android-obd-reader#126]
Please, **do not** do this yourself. I will take care of that.

**Comment by amouly** [comment]
Awesome, waiting the PR...

**Comment by nomwerp** [comment]
hey, some files seem still indented with 2 spaces    e.g.  src/main/java/com/github/pires/obd/reader/activity/MainActivity.java (but it is re-arranged), was that the intention?

**Comment by pires** [comment]
Nop. Idea may have screwed it. Will improve manually later.

**Comment by pires** [comment]
For some stupid reason, Android Studio had loaded the now removed Eclipse formatting settings file. Fixed and closed.
