### ISSUE TITLE
Missing @string/action_clear_codes?

### ISSUE THREAD

**Issue by Hippoish24** [pires/android-obd-reader#127]
What does ```@string/action_clear_codes``` in [menu\trouble_codes.xml](https://github.com/pires/android-obd-reader/blob/master/src/main/res/menu/trouble_codes.xml) reference?  It's not in [strings.xml](https://github.com/pires/android-obd-reader/blob/master/src/main/res/values/strings.xml), and neither myself nor Android Studio can find it elsewhere.  As a result, Gradle is unable to build the project.

On a related note, it appears that lines invoking the ObdReading constructors in [MainActivity.java](https://github.com/pires/android-obd-reader/blob/master/src/main/java/com/github/pires/obd/reader/activity/MainActivity.java) (180, 188) were not updated to include ```alt``` as arguments, which also causes a compile error.

(Seen in the latest commit as of this writing, 7e24b9397b)

**Comment by Pho3niX90** [comment]
It's this:

    <string name="action_clear_codes">Clear Codes</string>

And obdreadings fix is 

https://github.com/pires/android-obd-reader/pull/125/files

**Comment by nomwerp** [comment]
@Pho3niX90 I merged #128 for a quick fix while we sort out the code formatting

**Comment by Pho3niX90** [comment]
@nomwerp okay thats perfect

**Comment by Hippoish24** [comment]
Looks good; thank you!
