### ISSUE TITLE
min API level is missing

### ISSUE THREAD

**Issue by sytolk** [pires/android-obd-reader#140]
Its have String isEmpty function used:
https://github.com/pires/android-obd-reader/blob/master/src/main/java/com/github/pires/obd/reader/activity/TroubleCodesActivity.java#L192

I suppose that min API level will be 9 ?

AndroidManifest.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.github.pires.obd.reader"
    android:versionCode="13"
    android:versionName="2.0-RC2">
<uses-sdk
        android:minSdkVersion="9"
        android:targetSdkVersion="21"/>
```

**Comment by pires** [comment]
We can aim higher, say API Level 14.
