### ISSUE TITLE
Can't connect from HTC One

### ISSUE THREAD

**Issue by isgarsi** [pires/android-obd-reader#152]
Hi Pires,

I can connect with a mini ELM327 from several smartphones but I can't from a HTC One. It seems that there isn't any problem while It is connecting but when I try to get data from bluetooth socket, it returns a bluetooth exception (break pipe)

Could you help me with that?

Thanks in advance.

**Comment by pires** [comment]
Probably the phone is broken. There's little to nothing I can do to help here, I'm sorry.

**Comment by isgarsi** [comment]
I don't think so, because It can connect with other apps like torque. I'm going to try with your app android-obd-reader and will tell you the result.

Thanks

**Comment by isgarsi** [comment]
It didn't run with android-obd-reader app, but it runs in all other smartphones so I won't waste more time with that.

Thanks.
