### ISSUE TITLE
Service not binding after failure

### ISSUE THREAD

**Issue by Pho3niX90** [pires/android-obd-reader#158]
I noticed that the service refuses to bind again when the service has failed. For example. 
The app receives a bluetooth error and can no longer process info, stop service and then try to start again it it will do nothing. You have to clear app from memory to start again.

**Comment by pires** [comment]
Any logs related to the initial failure and the service failed binding?

**Comment by Pho3niX90** [comment]
No nothing. With my debugging it just doesn't happen, but no error logs. I am trying to figure out why the service doesn't bind / recreate unless the app gets a proper restart

**Comment by pires** [comment]
@Pho3niX90 ok will close this until you find proof this doesn't work as expected.
