### ISSUE TITLE
Failure in the execution of commands

### ISSUE THREAD

**Issue by omarpontis** [pires/android-obd-reader#16]
The communication between my hardware simulator and the app begins, but no commands are executed.
When i read "OK" everything goes fine. The problems comes later when i read "SEARCHING...". I get this message in logcat:
4800-4800/pt.lighthouselabs.obd.reader E/pt.lighthouselabs.obd.reader.io.ObdGatewayService﹕ Failed to run command. -> Invalid int: "0xSE"

Same speech for "STOPPED...". I get the same error:
4800-4800/pt.lighthouselabs.obd.reader E/pt.lighthouselabs.obd.reader.io.ObdGatewayService﹕ Failed to run command. -> Invalid int: "0xST"

**Comment by lokesh1219** [comment]
Hi, I am getting live data is perfect but when i click on GET DTC it throwing OBD command failure and list Data null , whta is the solution of it.

**Comment by lokesh1219** [comment]
is there any process to get dtc .
