### ISSUE TITLE
VIN - Binary result returned

### ISSUE THREAD

**Issue by KirbyJames** [pires/android-obd-reader#174]
Hi, I've rebuilt android-obd-reader-2.0-RC3 which I think contains obd-java-api-master 1.0-RC15 or RC14.

After looking at earlier VIN related prblems I've added ATH0 to the initialisation string.  However I still get (a fixed) binary value displayed for the VIN (except on about 1 in 10 occsaions when it does display the correct value).

I'd be grateful for any pointers as to what I might be doing wrong.

![vin](https://cloud.githubusercontent.com/assets/6604358/14114739/250e2306-f5d0-11e5-85c3-5b4169b11b99.png)

**Comment by Pho3niX90** [comment]
This is still an issue on my side as well. I am prepared to put up a $10 reward for a proper fix for the VIN.

**Comment by shareef593** [comment]
Add $10 from me

**Comment by Pho3niX90** [comment]
For all that are having this issue, please post your rawData vin here. I need to see what vins are being returned so that I can figure out one algorithm.

**Comment by KirbyJames** [comment]
Many thanks for returning to this issue.

Below are two VINs shown as both raw and hex

    euÂ¥Â¥Â£ÂµÂ¤ #3s#                               
    eÂ…Â„Ã”Â£ £ÂƒSs 

![hex](https://cloud.githubusercontent.com/assets/6604358/15178591/60762974-176e-11e6-8ff4-66577dfddbbb.png)

**Comment by KirbyJames** [comment]
Many thanks for returning to this issue.

Below are two VINs shown as both raw and hex

euÂ¥Â¥Â£ÂµÂ¤ #3s#                               
eÂ…Â„Ã”Â£ £ÂƒSs 
![hex](https://cloud.githubusercontent.com/assets/6604358/15178629/9613fba6-176e-11e6-9126-27a41204289c.png)

**Comment by Pho3niX90** [comment]
@kirbyjames
Could you please post your raw response from the obd. So that I can do tests?

**Comment by Pho3niX90** [comment]
@KirbyJames Pleaes try this project: http://goo.gl/uAcCK3
Replace the result string with your raw response. See if it's giving you the correct output

**Comment by KirbyJames** [comment]
Hi, I've added the code to VinCommand.java and rebuilt the app. Unfortunately it returns the same value ..

<img width="232" alt="capture" src="https://cloud.githubusercontent.com/assets/6604358/15186406/cf1981de-1794-11e6-9b7c-fe2605808b02.png">

**Comment by Pho3niX90** [comment]
@KirbyJames I will need your rawData response to rrsolve.

**Comment by Pho3niX90** [comment]
in calculated results. Instead of returning vin return tawData

**Comment by Pho3niX90** [comment]
sry I am in the phone. mean rawData

**Comment by Pho3niX90** [comment]
@KirbyJames 
Please add the following in you vin data
`Log.d("VinCommand.java", "rawdata: " + rawData);`

Like so:
![image](https://cloud.githubusercontent.com/assets/7858187/15187716/7de5c4a4-17a2-11e6-9f7a-f52221882408.png)

Then find the raw response in your logcat.

**Comment by KirbyJames** [comment]
Ah. I have realised that my build is using the github version of obd-java-api-master/.  I have downloaded the obd-java-api-master library - but I don't know how to modify the gradle configuration to use it in the build.

**Comment by Pho3niX90** [comment]
@KirbyJames I have no idea to be honest. I have completely moved away from gradle. 
@Pires do you know the answer to the above question?

**Comment by KirbyJames** [comment]
I've managed to re-build the app with the modified VinCommand.java
I've printed the rawdata value below ... and a valid 17-character Vin is returned :-)

rawdata: 0:4902015756571:5A5A5A314B5A422:57323233373237
    Vin: WVWZZZ1KZBW223727

rawdata: 0:4902015756571:5A5A5A314B5A422:57323233373237
    Vin: WVWZZZ1KZBW223727

**Comment by Pho3niX90** [comment]
@KirbyJames Awesome news! What vehicle was it used in, which country and what year model is the vehicle? This will help greatly in diagnosing further enchancements to the VIN.

**Comment by KirbyJames** [comment]
WVWZZZ1KZBW223727 is a 2011 VW Golf registered in the UK.
Will the update be included in an updated obd-java-api?

**Comment by Pho3niX90** [comment]
Then it's most def a can. on same restriction as we here in south africa are, except no emissions. 
Anyways, yes the changes will be added to the lib, pullrequest is located here -> https://github.com/pires/obd-java-api/pull/113

**Comment by pires** [comment]
I'll be releasing library RC16 as soon as @Pho3niX90 finishes an open PR and will update this project.

**Comment by pires** [comment]
Done.
