### ISSUE TITLE
Detect CAR AC(on/off) and Window(open/close) using OBD

### ISSUE THREAD

**Issue by pranaypatel512** [pires/android-obd-reader#175]
Is there any way to detect AC(air conditioner)  and Window(open/close) using OBD.

**Comment by Pho3niX90** [comment]
HI, please see https://en.wikipedia.org/wiki/OBD-II_PIDs#Mode_09

You will have to hack the canbus to achieve what  you need, not part of this project.

**Comment by pires** [comment]
I wish manufacturers would at least implement all standard PIDs. Thank you @Pho3niX90.
