### ISSUE TITLE
Missing ALTITUDE

### ISSUE THREAD

**Issue by jbits** [pires/android-obd-reader#176]
public class LogCSVWriter
private static final String[] NAMES_COLUMNS

**Comment by Pho3niX90** [comment]
@jbits could you please elaborate on the issue?

**Comment by jbits** [comment]
NAMES_COLUMNS is missing column name for ALTITUDE. 
LogCSVWriter writes out altitude:
`            crl = reading.getTimestamp() + ";" +
                    reading.getLatitude() + ";" +
                    reading.getLongitude() + ";" +
                    reading.getAltitude() + ";" +
                    reading.getVin() + ";";`

As a result all values past Longitude have wrong column heading.

**Comment by pires** [comment]
@jbits why don't you open a PR with a fix? Would be glad to merge.
