### ISSUE TITLE
Cant connect to the obd by bluetooth

### ISSUE THREAD

**Issue by yangwuan55** [pires/android-obd-reader#179]
The state is always return UNABLETOCONNECT.Please help me,thanks!

**Comment by Pho3niX90** [comment]
You are either selecting the incorrect device to connect to, or the device is faulty.

**Comment by pires** [comment]
What @Pho3niX90 said. This is a Bluetooth issue and not an app issue.

**Comment by yangwuan55** [comment]
Thanks.
I found the problem.

**Comment by Pho3niX90** [comment]
@yangwuan55 care to share what the problem was?

**Comment by yangwuan55** [comment]
@Pho3niX90 I use the simulator,and the simulator should set the agreement,I set the agreement and it can use.
