### ISSUE TITLE
Issue LogFile 0KB

### ISSUE THREAD

**Issue by galuhboy123** [pires/android-obd-reader#195]
hai my name is Boy (student)

i want to ask about log file that was created in SD card on directory called "OBDReaderLogs".
in that folder we should see log file from previous trip from obdreader progrom, But somehow after i try it, the file log was created but there is nothing on it (file 0 kb).

anyone could help please

thanks 

(sory for bad english)
grads BOY

**Comment by jbits** [comment]
Nothing obvious. I use logging a lot and it works. Your best bet is to debug it yourself.
