### ISSUE TITLE
Add battery support

### ISSUE THREAD

**Issue by guanlisheng** [pires/android-obd-reader#2]
such as AT RV to read the Voltage

**Comment by nomwerp** [comment]
isn't this one for pires/obd-java-api ? close this one and create an issue there?

**Comment by nomwerp** [comment]
nevermind, just checked and it is already there: pires/obd-java-api#3

**Comment by pires** [comment]
Yeah, I'm closing whenever that gets implemented.

**Comment by pires** [comment]
This has been implemented in `obd-java-api` v0.10, https://github.com/pires/obd-java-api/commit/f5c4361500558d9f80516a3b35263d4694fc8721. Anyone care to try it?

**Comment by Pho3niX90** [comment]
Works on one of my vehicles.

**Comment by pires** [comment]
Awesome!
