### ISSUE TITLE
add another unique id for upload get error (retrofit.RetrofitError: 500 Internal Server Error)

### ISSUE THREAD

**Issue by galuhboy123** [pires/android-obd-reader#200]
i want to add another unique id, i tried add some code on ObdReading.java  duplicating the vehicleid code and edit MainActivity.java to match the new code. the application still running well but the upload function return retrofit.RetrofitError: 500 Internal Server Error. can someone help me solve this, or tell me if there any other file i forget to modified. thanks in advance...  

sorry for bad english, i'm a student.

**Comment by Drjacky** [comment]
@galuhboy123 It's not this project issue. It's yours. Mentioned error means that there is problem on server side. check it via Postman. Anyway, [google that error](https://www.google.com/search?q=retrofit.RetrofitError%3A+500+Internal+Server+Error&oq=retrofit.RetrofitError%3A+500+Internal+Server+Error&aqs=chrome..69i57j69i61.465j0j7&sourceid=chrome&ie=UTF-8).
