### ISSUE TITLE
what is the output of DTCNumber command

### ISSUE THREAD

**Issue by aanchalharit** [pires/android-obd-reader#201]
Hi Pires , 

I have just started programming and want to create a ODB2 app. I came across this library and seeing the commands I saw DtcNumberCommand . I have not run it yet but can you please suggest will this command give me all the DTC codes? As there are hundreds of DTC codes how the interpretation of them will work here?

Thanks , 
Aanchal

**Comment by pires** [comment]
This is not a library but an Android app. The library sits at https://github.com/pires/obd-java-api and there you can find the implementation of said command.
