### ISSUE TITLE
get_data.php  sample

### ISSUE THREAD

**Issue by githubsrinath** [pires/android-obd-reader#203]
Is there any get_data.php sample program available to read and store the data in the centralized server.

If not... I will write my own get_data.php.  But I would like to know, what variables I need use in get_data.php in order to get the data from app?

Many Thanks
Srinath Rao

![1](https://cloud.githubusercontent.com/assets/4478246/21818899/90d5d29a-d78f-11e6-9c9a-2feb3965ca67.png)

**Comment by pires** [comment]
You can base your work in this https://github.com/pires/android-obd-reader/issues/147. But a github/google search would probably give you PHP code as well.

**Comment by M-Ahmad-sattar** [comment]
sir is still any referral information regarding this point?
