### ISSUE TITLE
Display OBD connection status in UI

### ISSUE THREAD

**Issue by pires** [pires/android-obd-reader#5]
**What steps will reproduce the problem?**
1. Start the application.
2. Watch the screen and try to tell if your phone can actually talk to the OBD reader.

**What is the expected output? What do you see instead?**
I would like to have a status message (e.g. in the main window) telling me whether an OBD reader has been found and the app can talk to it - in a way that is clear even to new users of the application.
Instead, I see a notification saying "ODB Connection has started". However, I get this on every app start, even when there is no OBD reader anywhere in sight, and the notification disappears as soon as I press "Start Live Data".

**What version of the product are you using? On what operating system?**
Currently using version 1.3, installed from f-droid.org. OS is CyanogenMod 10.1.0 on a Nexus S, with a generic ELM327 reader, in a 2005 Audi A4.

**Please provide any additional information below.**
Testing a successful connection with the OBD reader could be done by sending a universally supported PID (e.g. Mode 01 PID 00 - list supported PIDs) and checking for a valid response. Connection status can be:
- Connected - if we got a valid response
- Invalid response - if we got a response but it doesn't look like a valid response to the PID we sent (e.g. for Mode 01 PID 00, if the response length is not equal to 4 bytes).
- OBD device not found - if no Bluetooth connection to the selected OBD device could be established
- No device selected - if no device has been selected in Settings

**Comment by pires** [comment]
This is closed now @nomwerp, right?

**Comment by nomwerp** [comment]
well definitely not as fancy as described above , there is for example no status for successful OBD communication , but since nowadays the actual results is already printed to the screen in case of an communication error i.e. NODATA let's close this one and open a new issue for additional functionality (or bugs;)
