### ISSUE TITLE
wifi

### ISSUE THREAD

**Issue by a7medshe7ata** [pires/android-obd-reader#60]
i want to add support to this app to rub over wifi
from where i can start ?
what class should i edit to migrate from bluetooth to wifi

**Comment by pires** [comment]
https://github.com/pires/android-obd-reader/blob/master/src/main/java/pt/lighthouselabs/obd/reader/io/ObdGatewayService.java#L49

**Comment by simbu88** [comment]
I Need ODB-II communicate over wifi .if any code give help to me
