### ISSUE TITLE
add accelerometer data

### ISSUE THREAD

**Issue by nomwerp** [pires/android-obd-reader#69]
It would be great to have access to accelerometer data in the app (and especially future database uploads) , for example to correct for fuel usage for driving uphill or correlate engine load with power etc.

**Comment by pires** [comment]
I wish we could just get proper fuel consumption support.

**Comment by Pho3niX90** [comment]
Accelerometer wont be needed for proper fuel consumption. I have already made pull requests. The method will be to see how much fuel is actually injected and then calculate the fuel being burned. Most vehicles do have trims to actually show how the afr is being changed (example. Going uphil, going WOT ect)

**Comment by pires** [comment]
We'll see how that works out :)
