### ISSUE TITLE
Bluetooth is disabled after closing the app

### ISSUE THREAD

**Issue by FunThomas76** [pires/android-obd-reader#72]
Hi, 
normally my bluetooth is always on but after closing this app my bluetooth is turned off :(

best regards,
Thomas

**Comment by pires** [comment]
@elagin @nomwerp I believe this was added recently, right?

**Comment by elagin** [comment]
Yes recently been added. Now try to fix.

**Comment by pires** [comment]
Thanks @elagin. Waiting for a PR then ;-)

**Comment by elagin** [comment]
Ready  #73

**Comment by pires** [comment]
@FunThomas76 fix LGTM. Care to try it out and let us know if it worked?

**Comment by FunThomas76** [comment]
i could not believe that you could fix it that fast ;-) 
i have to rebuild today evening and will report you then

**Comment by pires** [comment]
@FunThomas76 reopening and waiting on your feedback to close the issue ;-)

**Comment by FunThomas76** [comment]
working as expected :)
after closing the app my bluetooth stays enabled like always
Thanx

**Comment by pires** [comment]
Awesome!
