### ISSUE TITLE
New UI based on Material Design

### ISSUE THREAD

**Issue by pires** [pires/android-obd-reader#80]

**Comment by pires** [comment]
Need help!

**Comment by nomwerp** [comment]
I guess it could make things pretty but it seems that android:Theme.Material requires API level 21 (current min is 10). since supposedly only 10% of devices use this is that something we want? or does it fall back gracefully? (although it might not install anymore)
https://developer.android.com/about/dashboards/index.html

**Comment by nomwerp** [comment]
to answer my own question:
from main/res/values/styles.xml
"Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here."

**Comment by nomwerp** [comment]
just applying the theme and deleting the background colours in favour of the defaults doesn't even look too bad: 


![device-2015-05-09-233637](https://cloud.githubusercontent.com/assets/10109262/7552144/5efc78f0-f6a4-11e4-8890-c3a87ba952e0.png)

**Comment by pires** [comment]
I guess it never looked as prettier :D

**Comment by nomwerp** [comment]
commit 8bebec600e  (still  looks as ugly as always on older versions )

but I'll play around for a bit with the new theme...

**Comment by pires** [comment]
Awesome! Thanks

**Comment by nomwerp** [comment]
Theme.Material.Light looks better in my opinion: 

![device-2015-05-10-113704](https://cloud.githubusercontent.com/assets/10109262/7553726/1205087c-f709-11e4-9264-10da2a49c380.png)


nomwerp/android-obd-reader@0a8bc8c806

I'm having trouble getting the fancy shadows to show up , setting elevation works in the preview but not on device

**Comment by fernando-costa** [comment]
i believe that you can expand compatibility using Android Support Library

http://developer.android.com/tools/support-library/index.html

**Comment by pires** [comment]
@nomwerp we're ready to close this one, are we not?
