### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by nomwerp** [pires/android-obd-reader#82]
we should have a icon!

with some hints from http://www.google.com/design/spec/style/icons.html#icons-product-icons
i've made an attempt at drawing a svg (here attached as 144X144):  

![ic_launcher](https://cloud.githubusercontent.com/assets/10109262/7633710/3407c00e-fa56-11e4-8bf9-2dfc11506c9c.png)

basic sprites from https://github.com/google/material-design-icons " released under an Attribution 4.0 International license." but it seems that the "Bluetooth SIG" also claims it as a trademark http://www.bluetooth.com/Pages/Trademarks.aspx  

I welcome harsh criticism on any aspect, the idea, colours , style, etc.

**Comment by pires** [comment]
Oh, so nice of you to actually get a new icon. It looks good :)

**Comment by nomwerp** [comment]
where would be a good place to put .svg?  my best bet is directly in src/main/res

**Comment by pires** [comment]
I have no idea.

**Comment by pires** [comment]
Did you fix this with #83? If so, next time close it please.

**Comment by nomwerp** [comment]
well if no complaints about the new icons i'd be happy to close...

**Comment by pires** [comment]
You merged it and were waiting on complains? :-D
