### ISSUE TITLE
Add full internationalization support

### ISSUE THREAD

**Issue by pires** [pires/android-obd-reader#90]

**Comment by nomwerp** [comment]
i think that's all strings in the UI, @amouly would you mind to do some more translation to spanish?

**Comment by amouly** [comment]
@nomwerp yes, I added a lot more Strings, but I have that issue with indentation, because I made some changes and can't merge directly. Maybe I can discard my changes on indentation and just pull the Strings.

**Comment by nomwerp** [comment]
yeah i'm afraid that the changes i did in  19fa27811ebb0b19147f4a2e077334689d820706 are causing the conflict,  could i ask you to prepare a pull request just for the changes you made in src/main/res/values-es/strings.xml  and  src/main/res/values/strings.xml ?  and I'll work work out what those strings are called now afterwards.  thanks.

**Comment by pires** [comment]
@nomwerp @amouly can you update me on this, please?

**Comment by amouly** [comment]
I think is mostly done. Right @nomwerp?

**Comment by pires** [comment]
Awesome!
