### ISSUE TITLE
Preferences XML file

### ISSUE THREAD

**Issue by amouly** [pires/android-obd-reader#91]
Why we have the preferences.xml file under "xml" folder? The standard way is to put it under "layout" folder.

**Comment by pires** [comment]
Good question. Historical reasons! Feel free to propose any changes.

**Comment by nomwerp** [comment]
actually, that seems to be right place: "You must save the XML file in the res/xml/ directory."

https://developer.android.com/guide/topics/ui/settings.html#DefiningPrefs
