### ISSUE TITLE
Repackage to com.github.pires.obd

### ISSUE THREAD

**Issue by pires** [pires/android-obd-reader#98]

**Comment by nomwerp** [comment]
we're on f-droid again with the new package name:
https://f-droid.org/repository/browse/?fdid=com.github.pires.obd.reader
note that for auto update to work in the future the tag name and android:versionName in the manifest must be absolutely identical (2.0-rc1 vs 2.0-RC1 ). 
for reference, any future modifications of the fdroid metadata can be made here: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.github.pires.obd.reader.txt

**Comment by pires** [comment]
Nice! Thanks
